#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : rubygem-bson
Version  : 3.2.6
Release  : 5
URL      : https://rubygems.org/downloads/bson-3.2.6.gem
Source0  : https://rubygems.org/downloads/bson-3.2.6.gem
Summary  : No detailed summary available
Group    : Development/Tools
License  : Apache-2.0
Requires: rubygem-bson-lib
BuildRequires : ruby
BuildRequires : rubygem-devise
BuildRequires : rubygem-diff-lcs
BuildRequires : rubygem-rdoc
BuildRequires : rubygem-rspec
BuildRequires : rubygem-rspec-core
BuildRequires : rubygem-rspec-expectations
BuildRequires : rubygem-rspec-mocks
BuildRequires : rubygem-rspec-support

%description
BSON [![Build Status](https://secure.travis-ci.org/mongodb/bson-ruby.png?branch=master&.png)](http://travis-ci.org/mongodb/bson-ruby)  [![Code Climate](https://codeclimate.com/github/mongodb/bson-ruby.png)](https://codeclimate.com/github/mongodb/bson-ruby) [![Coverage Status](https://coveralls.io/repos/mongodb/bson-ruby/badge.png?branch=master)](https://coveralls.io/r/mongodb/bson-ruby?branch=master) [![Inline docs](http://inch-ci.org/github/mongodb/bson-ruby.svg?branch=master)](http://inch-ci.org/github/mongodb/bson-ruby)
====

%package lib
Summary: lib components for the rubygem-bson package.
Group: Libraries

%description lib
lib components for the rubygem-bson package.


%prep
gem unpack %{SOURCE0}
%setup -q -D -T -n bson-3.2.6
gem spec %{SOURCE0} -l --ruby > rubygem-bson.gemspec

%build
gem build rubygem-bson.gemspec

%install
%global gem_dir $(ruby -e'puts Gem.default_dir')
gem install -V \
--local \
--force \
--install-dir .%{gem_dir} \
--bindir .%{_bindir} \
bson-3.2.6.gem

mkdir -p %{buildroot}%{gem_dir}
cp -pa .%{gem_dir}/* \
%{buildroot}%{gem_dir}

if [ -d .%{_bindir} ]; then
mkdir -p %{buildroot}%{_bindir}
cp -pa .%{_bindir}/* \
%{buildroot}%{_bindir}/
fi

%check
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost
pushd %{buildroot}%{gem_dir}/gems/bson-3.2.6
rspec -I.:lib spec/
popd


%files
%defattr(-,root,root,-)
/usr/lib64/ruby/gems/2.2.0/cache/bson-3.2.6.gem
/usr/lib64/ruby/gems/2.2.0/doc/bson-3.2.6/ri/BSON/Array/ClassMethods/cdesc-ClassMethods.ri
/usr/lib64/ruby/gems/2.2.0/doc/bson-3.2.6/ri/BSON/Array/ClassMethods/from_bson-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/bson-3.2.6/ri/BSON/Array/cdesc-Array.ri
/usr/lib64/ruby/gems/2.2.0/doc/bson-3.2.6/ri/BSON/Array/to_bson-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/bson-3.2.6/ri/BSON/Array/to_bson_normalized_value-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/bson-3.2.6/ri/BSON/Array/to_bson_object_id-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/bson-3.2.6/ri/BSON/Binary/%3d%3d-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/bson-3.2.6/ri/BSON/Binary/InvalidType/cdesc-InvalidType.ri
/usr/lib64/ruby/gems/2.2.0/doc/bson-3.2.6/ri/BSON/Binary/InvalidType/message-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/bson-3.2.6/ri/BSON/Binary/InvalidType/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/bson-3.2.6/ri/BSON/Binary/InvalidType/type-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/bson-3.2.6/ri/BSON/Binary/as_json-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/bson-3.2.6/ri/BSON/Binary/cdesc-Binary.ri
/usr/lib64/ruby/gems/2.2.0/doc/bson-3.2.6/ri/BSON/Binary/data-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/bson-3.2.6/ri/BSON/Binary/eql%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/bson-3.2.6/ri/BSON/Binary/from_bson-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/bson-3.2.6/ri/BSON/Binary/hash-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/bson-3.2.6/ri/BSON/Binary/inspect-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/bson-3.2.6/ri/BSON/Binary/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/bson-3.2.6/ri/BSON/Binary/to_bson-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/bson-3.2.6/ri/BSON/Binary/type-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/bson-3.2.6/ri/BSON/Binary/validate_type%21-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/bson-3.2.6/ri/BSON/Boolean/cdesc-Boolean.ri
/usr/lib64/ruby/gems/2.2.0/doc/bson-3.2.6/ri/BSON/Boolean/from_bson-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/bson-3.2.6/ri/BSON/Code/%3d%3d-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/bson-3.2.6/ri/BSON/Code/as_json-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/bson-3.2.6/ri/BSON/Code/cdesc-Code.ri
/usr/lib64/ruby/gems/2.2.0/doc/bson-3.2.6/ri/BSON/Code/from_bson-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/bson-3.2.6/ri/BSON/Code/javascript-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/bson-3.2.6/ri/BSON/Code/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/bson-3.2.6/ri/BSON/Code/to_bson-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/bson-3.2.6/ri/BSON/CodeWithScope/%3d%3d-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/bson-3.2.6/ri/BSON/CodeWithScope/as_json-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/bson-3.2.6/ri/BSON/CodeWithScope/cdesc-CodeWithScope.ri
/usr/lib64/ruby/gems/2.2.0/doc/bson-3.2.6/ri/BSON/CodeWithScope/from_bson-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/bson-3.2.6/ri/BSON/CodeWithScope/javascript-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/bson-3.2.6/ri/BSON/CodeWithScope/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/bson-3.2.6/ri/BSON/CodeWithScope/scope-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/bson-3.2.6/ri/BSON/CodeWithScope/to_bson-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/bson-3.2.6/ri/BSON/Date/bson_type-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/bson-3.2.6/ri/BSON/Date/cdesc-Date.ri
/usr/lib64/ruby/gems/2.2.0/doc/bson-3.2.6/ri/BSON/Date/to_bson-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/bson-3.2.6/ri/BSON/DateTime/cdesc-DateTime.ri
/usr/lib64/ruby/gems/2.2.0/doc/bson-3.2.6/ri/BSON/DateTime/to_bson-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/bson-3.2.6/ri/BSON/Document/%5b%5d%3d-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/bson-3.2.6/ri/BSON/Document/%5b%5d-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/bson-3.2.6/ri/BSON/Document/cdesc-Document.ri
/usr/lib64/ruby/gems/2.2.0/doc/bson-3.2.6/ri/BSON/Document/convert_key-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/bson-3.2.6/ri/BSON/Document/convert_value-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/bson-3.2.6/ri/BSON/Document/merge%21-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/bson-3.2.6/ri/BSON/Document/merge-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/bson-3.2.6/ri/BSON/Document/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/bson-3.2.6/ri/BSON/Document/update-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/bson-3.2.6/ri/BSON/Encodable/cdesc-Encodable.ri
/usr/lib64/ruby/gems/2.2.0/doc/bson-3.2.6/ri/BSON/Encodable/encode_binary_data_with_placeholder-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/bson-3.2.6/ri/BSON/Encodable/encode_with_placeholder_and_null-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/bson-3.2.6/ri/BSON/Environment/cdesc-Environment.ri
/usr/lib64/ruby/gems/2.2.0/doc/bson-3.2.6/ri/BSON/Environment/jruby%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/bson-3.2.6/ri/BSON/FalseClass/bson_type-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/bson-3.2.6/ri/BSON/FalseClass/cdesc-FalseClass.ri
/usr/lib64/ruby/gems/2.2.0/doc/bson-3.2.6/ri/BSON/FalseClass/to_bson-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/bson-3.2.6/ri/BSON/Float/ClassMethods/cdesc-ClassMethods.ri
/usr/lib64/ruby/gems/2.2.0/doc/bson-3.2.6/ri/BSON/Float/ClassMethods/from_bson-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/bson-3.2.6/ri/BSON/Float/ClassMethods/from_bson_double-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/bson-3.2.6/ri/BSON/Float/cdesc-Float.ri
/usr/lib64/ruby/gems/2.2.0/doc/bson-3.2.6/ri/BSON/Float/to_bson-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/bson-3.2.6/ri/BSON/Hash/ClassMethods/cdesc-ClassMethods.ri
/usr/lib64/ruby/gems/2.2.0/doc/bson-3.2.6/ri/BSON/Hash/ClassMethods/from_bson-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/bson-3.2.6/ri/BSON/Hash/cdesc-Hash.ri
/usr/lib64/ruby/gems/2.2.0/doc/bson-3.2.6/ri/BSON/Hash/to_bson-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/bson-3.2.6/ri/BSON/Hash/to_bson_normalized_value-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/bson-3.2.6/ri/BSON/Int32/cdesc-Int32.ri
/usr/lib64/ruby/gems/2.2.0/doc/bson-3.2.6/ri/BSON/Int32/from_bson-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/bson-3.2.6/ri/BSON/Int32/from_bson_int32-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/bson-3.2.6/ri/BSON/Int64/cdesc-Int64.ri
/usr/lib64/ruby/gems/2.2.0/doc/bson-3.2.6/ri/BSON/Int64/from_bson-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/bson-3.2.6/ri/BSON/Int64/from_bson_int64-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/bson-3.2.6/ri/BSON/Integer/append_bson_int32-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/bson-3.2.6/ri/BSON/Integer/bson_int32%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/bson-3.2.6/ri/BSON/Integer/bson_int64%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/bson-3.2.6/ri/BSON/Integer/bson_type-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/bson-3.2.6/ri/BSON/Integer/cdesc-Integer.ri
/usr/lib64/ruby/gems/2.2.0/doc/bson-3.2.6/ri/BSON/Integer/out_of_range%21-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/bson-3.2.6/ri/BSON/Integer/to_bson-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/bson-3.2.6/ri/BSON/Integer/to_bson_int32-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/bson-3.2.6/ri/BSON/Integer/to_bson_int64-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/bson-3.2.6/ri/BSON/Integer/to_bson_key-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/bson-3.2.6/ri/BSON/InvalidKey/cdesc-InvalidKey.ri
/usr/lib64/ruby/gems/2.2.0/doc/bson-3.2.6/ri/BSON/InvalidKey/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/bson-3.2.6/ri/BSON/JSON/cdesc-JSON.ri
/usr/lib64/ruby/gems/2.2.0/doc/bson-3.2.6/ri/BSON/JSON/to_json-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/bson-3.2.6/ri/BSON/MaxKey/%3c%3d%3e-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/bson-3.2.6/ri/BSON/MaxKey/as_json-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/bson-3.2.6/ri/BSON/MaxKey/cdesc-MaxKey.ri
/usr/lib64/ruby/gems/2.2.0/doc/bson-3.2.6/ri/BSON/MinKey/%3c%3d%3e-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/bson-3.2.6/ri/BSON/MinKey/as_json-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/bson-3.2.6/ri/BSON/MinKey/cdesc-MinKey.ri
/usr/lib64/ruby/gems/2.2.0/doc/bson-3.2.6/ri/BSON/NilClass/ClassMethods/cdesc-ClassMethods.ri
/usr/lib64/ruby/gems/2.2.0/doc/bson-3.2.6/ri/BSON/NilClass/ClassMethods/from_bson-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/bson-3.2.6/ri/BSON/NilClass/cdesc-NilClass.ri
/usr/lib64/ruby/gems/2.2.0/doc/bson-3.2.6/ri/BSON/NilClass/to_bson-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/bson-3.2.6/ri/BSON/Object/cdesc-Object.ri
/usr/lib64/ruby/gems/2.2.0/doc/bson-3.2.6/ri/BSON/Object/to_bson_key-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/bson-3.2.6/ri/BSON/Object/to_bson_normalized_key-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/bson-3.2.6/ri/BSON/Object/to_bson_normalized_value-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/bson-3.2.6/ri/BSON/ObjectId-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/bson-3.2.6/ri/BSON/ObjectId/%3c%3d%3e-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/bson-3.2.6/ri/BSON/ObjectId/%3d%3d%3d-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/bson-3.2.6/ri/BSON/ObjectId/%3d%3d-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/bson-3.2.6/ri/BSON/ObjectId/Generator/cdesc-Generator.ri
/usr/lib64/ruby/gems/2.2.0/doc/bson-3.2.6/ri/BSON/ObjectId/Generator/generate-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/bson-3.2.6/ri/BSON/ObjectId/Generator/machine_id-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/bson-3.2.6/ri/BSON/ObjectId/Generator/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/bson-3.2.6/ri/BSON/ObjectId/Generator/next_object_id-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/bson-3.2.6/ri/BSON/ObjectId/Generator/process_id-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/bson-3.2.6/ri/BSON/ObjectId/Invalid/cdesc-Invalid.ri
/usr/lib64/ruby/gems/2.2.0/doc/bson-3.2.6/ri/BSON/ObjectId/as_json-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/bson-3.2.6/ri/BSON/ObjectId/cdesc-ObjectId.ri
/usr/lib64/ruby/gems/2.2.0/doc/bson-3.2.6/ri/BSON/ObjectId/eql%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/bson-3.2.6/ri/BSON/ObjectId/from_bson-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/bson-3.2.6/ri/BSON/ObjectId/from_data-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/bson-3.2.6/ri/BSON/ObjectId/from_string-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/bson-3.2.6/ri/BSON/ObjectId/from_time-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/bson-3.2.6/ri/BSON/ObjectId/generation_time-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/bson-3.2.6/ri/BSON/ObjectId/hash-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/bson-3.2.6/ri/BSON/ObjectId/inspect-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/bson-3.2.6/ri/BSON/ObjectId/legal%3f-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/bson-3.2.6/ri/BSON/ObjectId/marshal_dump-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/bson-3.2.6/ri/BSON/ObjectId/marshal_load-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/bson-3.2.6/ri/BSON/ObjectId/repair-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/bson-3.2.6/ri/BSON/ObjectId/repair-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/bson-3.2.6/ri/BSON/ObjectId/to_bson-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/bson-3.2.6/ri/BSON/ObjectId/to_s-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/bson-3.2.6/ri/BSON/ObjectId/to_str-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/bson-3.2.6/ri/BSON/Regexp/ClassMethods/cdesc-ClassMethods.ri
/usr/lib64/ruby/gems/2.2.0/doc/bson-3.2.6/ri/BSON/Regexp/ClassMethods/from_bson-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/bson-3.2.6/ri/BSON/Regexp/Raw/cdesc-Raw.ri
/usr/lib64/ruby/gems/2.2.0/doc/bson-3.2.6/ri/BSON/Regexp/Raw/compile-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/bson-3.2.6/ri/BSON/Regexp/Raw/method_missing-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/bson-3.2.6/ri/BSON/Regexp/Raw/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/bson-3.2.6/ri/BSON/Regexp/Raw/options-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/bson-3.2.6/ri/BSON/Regexp/Raw/pattern-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/bson-3.2.6/ri/BSON/Regexp/Raw/respond_to%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/bson-3.2.6/ri/BSON/Regexp/as_json-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/bson-3.2.6/ri/BSON/Regexp/bson_extended-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/bson-3.2.6/ri/BSON/Regexp/bson_ignorecase-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/bson-3.2.6/ri/BSON/Regexp/bson_multiline-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/bson-3.2.6/ri/BSON/Regexp/bson_options-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/bson-3.2.6/ri/BSON/Regexp/cdesc-Regexp.ri
/usr/lib64/ruby/gems/2.2.0/doc/bson-3.2.6/ri/BSON/Regexp/to_bson-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/bson-3.2.6/ri/BSON/Registry/cdesc-Registry.ri
/usr/lib64/ruby/gems/2.2.0/doc/bson-3.2.6/ri/BSON/Registry/define_type_reader-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/bson-3.2.6/ri/BSON/Registry/get-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/bson-3.2.6/ri/BSON/Registry/register-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/bson-3.2.6/ri/BSON/Specialized/%3d%3d-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/bson-3.2.6/ri/BSON/Specialized/ClassMethods/cdesc-ClassMethods.ri
/usr/lib64/ruby/gems/2.2.0/doc/bson-3.2.6/ri/BSON/Specialized/ClassMethods/from_bson-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/bson-3.2.6/ri/BSON/Specialized/cdesc-Specialized.ri
/usr/lib64/ruby/gems/2.2.0/doc/bson-3.2.6/ri/BSON/Specialized/included-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/bson-3.2.6/ri/BSON/Specialized/to_bson-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/bson-3.2.6/ri/BSON/String/ClassMethods/cdesc-ClassMethods.ri
/usr/lib64/ruby/gems/2.2.0/doc/bson-3.2.6/ri/BSON/String/ClassMethods/from_bson-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/bson-3.2.6/ri/BSON/String/cdesc-String.ri
/usr/lib64/ruby/gems/2.2.0/doc/bson-3.2.6/ri/BSON/String/check_for_illegal_characters%21-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/bson-3.2.6/ri/BSON/String/from_bson_string-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/bson-3.2.6/ri/BSON/String/set_int32-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/bson-3.2.6/ri/BSON/String/to_bson-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/bson-3.2.6/ri/BSON/String/to_bson_cstring-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/bson-3.2.6/ri/BSON/String/to_bson_key-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/bson-3.2.6/ri/BSON/String/to_bson_object_id-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/bson-3.2.6/ri/BSON/String/to_bson_string-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/bson-3.2.6/ri/BSON/String/to_hex_string-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/bson-3.2.6/ri/BSON/String/to_utf8_binary-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/bson-3.2.6/ri/BSON/Symbol/ClassMethods/cdesc-ClassMethods.ri
/usr/lib64/ruby/gems/2.2.0/doc/bson-3.2.6/ri/BSON/Symbol/ClassMethods/from_bson-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/bson-3.2.6/ri/BSON/Symbol/cdesc-Symbol.ri
/usr/lib64/ruby/gems/2.2.0/doc/bson-3.2.6/ri/BSON/Symbol/to_bson-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/bson-3.2.6/ri/BSON/Symbol/to_bson_key-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/bson-3.2.6/ri/BSON/Symbol/to_bson_normalized_key-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/bson-3.2.6/ri/BSON/Time/ClassMethods/cdesc-ClassMethods.ri
/usr/lib64/ruby/gems/2.2.0/doc/bson-3.2.6/ri/BSON/Time/ClassMethods/from_bson-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/bson-3.2.6/ri/BSON/Time/cdesc-Time.ri
/usr/lib64/ruby/gems/2.2.0/doc/bson-3.2.6/ri/BSON/Time/to_bson-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/bson-3.2.6/ri/BSON/Timestamp/%3d%3d-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/bson-3.2.6/ri/BSON/Timestamp/as_json-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/bson-3.2.6/ri/BSON/Timestamp/cdesc-Timestamp.ri
/usr/lib64/ruby/gems/2.2.0/doc/bson-3.2.6/ri/BSON/Timestamp/from_bson-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/bson-3.2.6/ri/BSON/Timestamp/increment-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/bson-3.2.6/ri/BSON/Timestamp/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/bson-3.2.6/ri/BSON/Timestamp/seconds-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/bson-3.2.6/ri/BSON/Timestamp/to_bson-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/bson-3.2.6/ri/BSON/TrueClass/bson_type-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/bson-3.2.6/ri/BSON/TrueClass/cdesc-TrueClass.ri
/usr/lib64/ruby/gems/2.2.0/doc/bson-3.2.6/ri/BSON/TrueClass/to_bson-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/bson-3.2.6/ri/BSON/Undefined/%3d%3d-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/bson-3.2.6/ri/BSON/Undefined/cdesc-Undefined.ri
/usr/lib64/ruby/gems/2.2.0/doc/bson-3.2.6/ri/BSON/Undefined/from_bson-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/bson-3.2.6/ri/BSON/Undefined/to_bson-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/bson-3.2.6/ri/BSON/cdesc-BSON.ri
/usr/lib64/ruby/gems/2.2.0/doc/bson-3.2.6/ri/cache.ri
/usr/lib64/ruby/gems/2.2.0/doc/bson-3.2.6/ri/ext/bson/page-Makefile.ri
/usr/lib64/ruby/gems/2.2.0/doc/bson-3.2.6/ri/unknown/cdesc-unknown.ri
/usr/lib64/ruby/gems/2.2.0/extensions/x86_64-linux/2.2.0/bson-3.2.6/gem.build_complete
/usr/lib64/ruby/gems/2.2.0/extensions/x86_64-linux/2.2.0/bson-3.2.6/gem_make.out
/usr/lib64/ruby/gems/2.2.0/gems/bson-3.2.6/CHANGELOG.md
/usr/lib64/ruby/gems/2.2.0/gems/bson-3.2.6/CONTRIBUTING.md
/usr/lib64/ruby/gems/2.2.0/gems/bson-3.2.6/LICENSE
/usr/lib64/ruby/gems/2.2.0/gems/bson-3.2.6/NOTICE
/usr/lib64/ruby/gems/2.2.0/gems/bson-3.2.6/README.md
/usr/lib64/ruby/gems/2.2.0/gems/bson-3.2.6/Rakefile
/usr/lib64/ruby/gems/2.2.0/gems/bson-3.2.6/ext/bson/.RUBYARCHDIR.time
/usr/lib64/ruby/gems/2.2.0/gems/bson-3.2.6/ext/bson/Makefile
/usr/lib64/ruby/gems/2.2.0/gems/bson-3.2.6/ext/bson/extconf.rb
/usr/lib64/ruby/gems/2.2.0/gems/bson-3.2.6/ext/bson/native.c
/usr/lib64/ruby/gems/2.2.0/gems/bson-3.2.6/ext/bson/native.o
/usr/lib64/ruby/gems/2.2.0/gems/bson-3.2.6/lib/bson.rb
/usr/lib64/ruby/gems/2.2.0/gems/bson-3.2.6/lib/bson/array.rb
/usr/lib64/ruby/gems/2.2.0/gems/bson-3.2.6/lib/bson/binary.rb
/usr/lib64/ruby/gems/2.2.0/gems/bson-3.2.6/lib/bson/boolean.rb
/usr/lib64/ruby/gems/2.2.0/gems/bson-3.2.6/lib/bson/code.rb
/usr/lib64/ruby/gems/2.2.0/gems/bson-3.2.6/lib/bson/code_with_scope.rb
/usr/lib64/ruby/gems/2.2.0/gems/bson-3.2.6/lib/bson/date.rb
/usr/lib64/ruby/gems/2.2.0/gems/bson-3.2.6/lib/bson/date_time.rb
/usr/lib64/ruby/gems/2.2.0/gems/bson-3.2.6/lib/bson/document.rb
/usr/lib64/ruby/gems/2.2.0/gems/bson-3.2.6/lib/bson/encodable.rb
/usr/lib64/ruby/gems/2.2.0/gems/bson-3.2.6/lib/bson/environment.rb
/usr/lib64/ruby/gems/2.2.0/gems/bson-3.2.6/lib/bson/false_class.rb
/usr/lib64/ruby/gems/2.2.0/gems/bson-3.2.6/lib/bson/float.rb
/usr/lib64/ruby/gems/2.2.0/gems/bson-3.2.6/lib/bson/hash.rb
/usr/lib64/ruby/gems/2.2.0/gems/bson-3.2.6/lib/bson/int32.rb
/usr/lib64/ruby/gems/2.2.0/gems/bson-3.2.6/lib/bson/int64.rb
/usr/lib64/ruby/gems/2.2.0/gems/bson-3.2.6/lib/bson/integer.rb
/usr/lib64/ruby/gems/2.2.0/gems/bson-3.2.6/lib/bson/json.rb
/usr/lib64/ruby/gems/2.2.0/gems/bson-3.2.6/lib/bson/max_key.rb
/usr/lib64/ruby/gems/2.2.0/gems/bson-3.2.6/lib/bson/min_key.rb
/usr/lib64/ruby/gems/2.2.0/gems/bson-3.2.6/lib/bson/nil_class.rb
/usr/lib64/ruby/gems/2.2.0/gems/bson-3.2.6/lib/bson/object.rb
/usr/lib64/ruby/gems/2.2.0/gems/bson-3.2.6/lib/bson/object_id.rb
/usr/lib64/ruby/gems/2.2.0/gems/bson-3.2.6/lib/bson/regexp.rb
/usr/lib64/ruby/gems/2.2.0/gems/bson-3.2.6/lib/bson/registry.rb
/usr/lib64/ruby/gems/2.2.0/gems/bson-3.2.6/lib/bson/specialized.rb
/usr/lib64/ruby/gems/2.2.0/gems/bson-3.2.6/lib/bson/string.rb
/usr/lib64/ruby/gems/2.2.0/gems/bson-3.2.6/lib/bson/symbol.rb
/usr/lib64/ruby/gems/2.2.0/gems/bson-3.2.6/lib/bson/time.rb
/usr/lib64/ruby/gems/2.2.0/gems/bson-3.2.6/lib/bson/timestamp.rb
/usr/lib64/ruby/gems/2.2.0/gems/bson-3.2.6/lib/bson/true_class.rb
/usr/lib64/ruby/gems/2.2.0/gems/bson-3.2.6/lib/bson/undefined.rb
/usr/lib64/ruby/gems/2.2.0/gems/bson-3.2.6/lib/bson/version.rb
/usr/lib64/ruby/gems/2.2.0/gems/bson-3.2.6/spec/bson/array_spec.rb
/usr/lib64/ruby/gems/2.2.0/gems/bson-3.2.6/spec/bson/binary_spec.rb
/usr/lib64/ruby/gems/2.2.0/gems/bson-3.2.6/spec/bson/boolean_spec.rb
/usr/lib64/ruby/gems/2.2.0/gems/bson-3.2.6/spec/bson/code_spec.rb
/usr/lib64/ruby/gems/2.2.0/gems/bson-3.2.6/spec/bson/code_with_scope_spec.rb
/usr/lib64/ruby/gems/2.2.0/gems/bson-3.2.6/spec/bson/date_spec.rb
/usr/lib64/ruby/gems/2.2.0/gems/bson-3.2.6/spec/bson/date_time_spec.rb
/usr/lib64/ruby/gems/2.2.0/gems/bson-3.2.6/spec/bson/document_spec.rb
/usr/lib64/ruby/gems/2.2.0/gems/bson-3.2.6/spec/bson/false_class_spec.rb
/usr/lib64/ruby/gems/2.2.0/gems/bson-3.2.6/spec/bson/float_spec.rb
/usr/lib64/ruby/gems/2.2.0/gems/bson-3.2.6/spec/bson/hash_spec.rb
/usr/lib64/ruby/gems/2.2.0/gems/bson-3.2.6/spec/bson/int32_spec.rb
/usr/lib64/ruby/gems/2.2.0/gems/bson-3.2.6/spec/bson/int64_spec.rb
/usr/lib64/ruby/gems/2.2.0/gems/bson-3.2.6/spec/bson/integer_spec.rb
/usr/lib64/ruby/gems/2.2.0/gems/bson-3.2.6/spec/bson/json_spec.rb
/usr/lib64/ruby/gems/2.2.0/gems/bson-3.2.6/spec/bson/max_key_spec.rb
/usr/lib64/ruby/gems/2.2.0/gems/bson-3.2.6/spec/bson/min_key_spec.rb
/usr/lib64/ruby/gems/2.2.0/gems/bson-3.2.6/spec/bson/nil_class_spec.rb
/usr/lib64/ruby/gems/2.2.0/gems/bson-3.2.6/spec/bson/object_id_spec.rb
/usr/lib64/ruby/gems/2.2.0/gems/bson-3.2.6/spec/bson/object_spec.rb
/usr/lib64/ruby/gems/2.2.0/gems/bson-3.2.6/spec/bson/regexp_spec.rb
/usr/lib64/ruby/gems/2.2.0/gems/bson-3.2.6/spec/bson/registry_spec.rb
/usr/lib64/ruby/gems/2.2.0/gems/bson-3.2.6/spec/bson/string_spec.rb
/usr/lib64/ruby/gems/2.2.0/gems/bson-3.2.6/spec/bson/symbol_spec.rb
/usr/lib64/ruby/gems/2.2.0/gems/bson-3.2.6/spec/bson/time_spec.rb
/usr/lib64/ruby/gems/2.2.0/gems/bson-3.2.6/spec/bson/timestamp_spec.rb
/usr/lib64/ruby/gems/2.2.0/gems/bson-3.2.6/spec/bson/true_class_spec.rb
/usr/lib64/ruby/gems/2.2.0/gems/bson-3.2.6/spec/bson/undefined_spec.rb
/usr/lib64/ruby/gems/2.2.0/gems/bson-3.2.6/spec/bson_spec.rb
/usr/lib64/ruby/gems/2.2.0/gems/bson-3.2.6/spec/spec_helper.rb
/usr/lib64/ruby/gems/2.2.0/gems/bson-3.2.6/spec/support/shared_examples.rb
/usr/lib64/ruby/gems/2.2.0/specifications/bson-3.2.6.gemspec

%files lib
%defattr(-,root,root,-)
/usr/lib64/ruby/gems/2.2.0/extensions/x86_64-linux/2.2.0/bson-3.2.6/native.so
/usr/lib64/ruby/gems/2.2.0/gems/bson-3.2.6/ext/bson/native.so
/usr/lib64/ruby/gems/2.2.0/gems/bson-3.2.6/lib/native.so
