#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : rubygem-bson
Version  : 4.1.1
Release  : 9
URL      : https://rubygems.org/downloads/bson-4.1.1.gem
Source0  : https://rubygems.org/downloads/bson-4.1.1.gem
Summary  : No detailed summary available
Group    : Development/Tools
License  : Apache-2.0
Requires: rubygem-bson-lib
BuildRequires : gmp-dev
BuildRequires : ruby
BuildRequires : rubygem-devise
BuildRequires : rubygem-diff-lcs
BuildRequires : rubygem-rdoc
BuildRequires : rubygem-rspec
BuildRequires : rubygem-rspec-core
BuildRequires : rubygem-rspec-expectations
BuildRequires : rubygem-rspec-mocks
BuildRequires : rubygem-rspec-support

%description
BSON [![Build Status](https://secure.travis-ci.org/mongodb/bson-ruby.png?branch=master&.png)](http://travis-ci.org/mongodb/bson-ruby)  [![Code Climate](https://codeclimate.com/github/mongodb/bson-ruby.png)](https://codeclimate.com/github/mongodb/bson-ruby) [![Coverage Status](https://coveralls.io/repos/mongodb/bson-ruby/badge.png?branch=master)](https://coveralls.io/r/mongodb/bson-ruby?branch=master) [![Inline docs](http://inch-ci.org/github/mongodb/bson-ruby.svg?branch=master)](http://inch-ci.org/github/mongodb/bson-ruby)
====

%package lib
Summary: lib components for the rubygem-bson package.
Group: Libraries

%description lib
lib components for the rubygem-bson package.


%prep
gem unpack %{SOURCE0}
%setup -q -D -T -n bson-4.1.1
gem spec %{SOURCE0} -l --ruby > rubygem-bson.gemspec

%build
export LANG=C
gem build rubygem-bson.gemspec

%install
%global gem_dir $(ruby -e'puts Gem.default_dir')
gem install -V \
--local \
--force \
--install-dir .%{gem_dir} \
--bindir .%{_bindir} \
bson-4.1.1.gem

mkdir -p %{buildroot}%{gem_dir}
cp -pa .%{gem_dir}/* \
%{buildroot}%{gem_dir}

if [ -d .%{_bindir} ]; then
mkdir -p %{buildroot}%{_bindir}
cp -pa .%{_bindir}/* \
%{buildroot}%{_bindir}/
fi

%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost
pushd %{buildroot}%{gem_dir}/gems/bson-4.1.1
rspec -I.:lib spec/
popd


%files
%defattr(-,root,root,-)
/usr/lib64/ruby/gems/2.3.0/cache/bson-4.1.1.gem
/usr/lib64/ruby/gems/2.3.0/extensions/x86_64-linux/2.3.0/bson-4.1.1/gem.build_complete
/usr/lib64/ruby/gems/2.3.0/extensions/x86_64-linux/2.3.0/bson-4.1.1/gem_make.out
/usr/lib64/ruby/gems/2.3.0/gems/bson-4.1.1/CHANGELOG.md
/usr/lib64/ruby/gems/2.3.0/gems/bson-4.1.1/CONTRIBUTING.md
/usr/lib64/ruby/gems/2.3.0/gems/bson-4.1.1/LICENSE
/usr/lib64/ruby/gems/2.3.0/gems/bson-4.1.1/NOTICE
/usr/lib64/ruby/gems/2.3.0/gems/bson-4.1.1/README.md
/usr/lib64/ruby/gems/2.3.0/gems/bson-4.1.1/Rakefile
/usr/lib64/ruby/gems/2.3.0/gems/bson-4.1.1/ext/bson/.RUBYARCHDIR.time
/usr/lib64/ruby/gems/2.3.0/gems/bson-4.1.1/ext/bson/Makefile
/usr/lib64/ruby/gems/2.3.0/gems/bson-4.1.1/ext/bson/extconf.rb
/usr/lib64/ruby/gems/2.3.0/gems/bson-4.1.1/ext/bson/native-endian.h
/usr/lib64/ruby/gems/2.3.0/gems/bson-4.1.1/ext/bson/native.c
/usr/lib64/ruby/gems/2.3.0/gems/bson-4.1.1/ext/bson/native.o
/usr/lib64/ruby/gems/2.3.0/gems/bson-4.1.1/lib/bson.rb
/usr/lib64/ruby/gems/2.3.0/gems/bson-4.1.1/lib/bson/array.rb
/usr/lib64/ruby/gems/2.3.0/gems/bson-4.1.1/lib/bson/binary.rb
/usr/lib64/ruby/gems/2.3.0/gems/bson-4.1.1/lib/bson/boolean.rb
/usr/lib64/ruby/gems/2.3.0/gems/bson-4.1.1/lib/bson/code.rb
/usr/lib64/ruby/gems/2.3.0/gems/bson-4.1.1/lib/bson/code_with_scope.rb
/usr/lib64/ruby/gems/2.3.0/gems/bson-4.1.1/lib/bson/config.rb
/usr/lib64/ruby/gems/2.3.0/gems/bson-4.1.1/lib/bson/date.rb
/usr/lib64/ruby/gems/2.3.0/gems/bson-4.1.1/lib/bson/date_time.rb
/usr/lib64/ruby/gems/2.3.0/gems/bson-4.1.1/lib/bson/document.rb
/usr/lib64/ruby/gems/2.3.0/gems/bson-4.1.1/lib/bson/environment.rb
/usr/lib64/ruby/gems/2.3.0/gems/bson-4.1.1/lib/bson/false_class.rb
/usr/lib64/ruby/gems/2.3.0/gems/bson-4.1.1/lib/bson/float.rb
/usr/lib64/ruby/gems/2.3.0/gems/bson-4.1.1/lib/bson/hash.rb
/usr/lib64/ruby/gems/2.3.0/gems/bson-4.1.1/lib/bson/int32.rb
/usr/lib64/ruby/gems/2.3.0/gems/bson-4.1.1/lib/bson/int64.rb
/usr/lib64/ruby/gems/2.3.0/gems/bson-4.1.1/lib/bson/integer.rb
/usr/lib64/ruby/gems/2.3.0/gems/bson-4.1.1/lib/bson/json.rb
/usr/lib64/ruby/gems/2.3.0/gems/bson-4.1.1/lib/bson/max_key.rb
/usr/lib64/ruby/gems/2.3.0/gems/bson-4.1.1/lib/bson/min_key.rb
/usr/lib64/ruby/gems/2.3.0/gems/bson-4.1.1/lib/bson/nil_class.rb
/usr/lib64/ruby/gems/2.3.0/gems/bson-4.1.1/lib/bson/object.rb
/usr/lib64/ruby/gems/2.3.0/gems/bson-4.1.1/lib/bson/object_id.rb
/usr/lib64/ruby/gems/2.3.0/gems/bson-4.1.1/lib/bson/regexp.rb
/usr/lib64/ruby/gems/2.3.0/gems/bson-4.1.1/lib/bson/registry.rb
/usr/lib64/ruby/gems/2.3.0/gems/bson-4.1.1/lib/bson/specialized.rb
/usr/lib64/ruby/gems/2.3.0/gems/bson-4.1.1/lib/bson/string.rb
/usr/lib64/ruby/gems/2.3.0/gems/bson-4.1.1/lib/bson/symbol.rb
/usr/lib64/ruby/gems/2.3.0/gems/bson-4.1.1/lib/bson/time.rb
/usr/lib64/ruby/gems/2.3.0/gems/bson-4.1.1/lib/bson/timestamp.rb
/usr/lib64/ruby/gems/2.3.0/gems/bson-4.1.1/lib/bson/true_class.rb
/usr/lib64/ruby/gems/2.3.0/gems/bson-4.1.1/lib/bson/undefined.rb
/usr/lib64/ruby/gems/2.3.0/gems/bson-4.1.1/lib/bson/version.rb
/usr/lib64/ruby/gems/2.3.0/gems/bson-4.1.1/spec/bson/array_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/bson-4.1.1/spec/bson/binary_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/bson-4.1.1/spec/bson/boolean_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/bson-4.1.1/spec/bson/byte_buffer_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/bson-4.1.1/spec/bson/code_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/bson-4.1.1/spec/bson/code_with_scope_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/bson-4.1.1/spec/bson/config_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/bson-4.1.1/spec/bson/date_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/bson-4.1.1/spec/bson/date_time_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/bson-4.1.1/spec/bson/document_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/bson-4.1.1/spec/bson/false_class_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/bson-4.1.1/spec/bson/float_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/bson-4.1.1/spec/bson/hash_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/bson-4.1.1/spec/bson/int32_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/bson-4.1.1/spec/bson/int64_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/bson-4.1.1/spec/bson/integer_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/bson-4.1.1/spec/bson/json_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/bson-4.1.1/spec/bson/max_key_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/bson-4.1.1/spec/bson/min_key_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/bson-4.1.1/spec/bson/nil_class_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/bson-4.1.1/spec/bson/object_id_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/bson-4.1.1/spec/bson/object_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/bson-4.1.1/spec/bson/regexp_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/bson-4.1.1/spec/bson/registry_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/bson-4.1.1/spec/bson/string_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/bson-4.1.1/spec/bson/symbol_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/bson-4.1.1/spec/bson/time_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/bson-4.1.1/spec/bson/timestamp_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/bson-4.1.1/spec/bson/true_class_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/bson-4.1.1/spec/bson/undefined_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/bson-4.1.1/spec/bson_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/bson-4.1.1/spec/spec_helper.rb
/usr/lib64/ruby/gems/2.3.0/gems/bson-4.1.1/spec/support/shared_examples.rb
/usr/lib64/ruby/gems/2.3.0/specifications/bson-4.1.1.gemspec

%files lib
%defattr(-,root,root,-)
/usr/lib64/ruby/gems/2.3.0/extensions/x86_64-linux/2.3.0/bson-4.1.1/native.so
/usr/lib64/ruby/gems/2.3.0/gems/bson-4.1.1/ext/bson/native.so
/usr/lib64/ruby/gems/2.3.0/gems/bson-4.1.1/lib/native.so
