#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : rubygem-bson
Version  : 3.2.6
Release  : 7
URL      : https://rubygems.org/downloads/bson-3.2.6.gem
Source0  : https://rubygems.org/downloads/bson-3.2.6.gem
Summary  : No detailed summary available
Group    : Development/Tools
License  : Apache-2.0
Requires: rubygem-bson-lib
BuildRequires : ruby
BuildRequires : rubygem-devise
BuildRequires : rubygem-diff-lcs
BuildRequires : rubygem-rdoc
BuildRequires : rubygem-rspec
BuildRequires : rubygem-rspec-core
BuildRequires : rubygem-rspec-expectations
BuildRequires : rubygem-rspec-mocks
BuildRequires : rubygem-rspec-support

%description
BSON [![Build Status](https://secure.travis-ci.org/mongodb/bson-ruby.png?branch=master&.png)](http://travis-ci.org/mongodb/bson-ruby)  [![Code Climate](https://codeclimate.com/github/mongodb/bson-ruby.png)](https://codeclimate.com/github/mongodb/bson-ruby) [![Coverage Status](https://coveralls.io/repos/mongodb/bson-ruby/badge.png?branch=master)](https://coveralls.io/r/mongodb/bson-ruby?branch=master) [![Inline docs](http://inch-ci.org/github/mongodb/bson-ruby.svg?branch=master)](http://inch-ci.org/github/mongodb/bson-ruby)
====

%package lib
Summary: lib components for the rubygem-bson package.
Group: Libraries

%description lib
lib components for the rubygem-bson package.


%prep
gem unpack %{SOURCE0}
%setup -q -D -T -n bson-3.2.6
gem spec %{SOURCE0} -l --ruby > rubygem-bson.gemspec

%build
gem build rubygem-bson.gemspec

%install
%global gem_dir $(ruby -e'puts Gem.default_dir')
gem install -V \
--local \
--force \
--install-dir .%{gem_dir} \
--bindir .%{_bindir} \
bson-3.2.6.gem

mkdir -p %{buildroot}%{gem_dir}
cp -pa .%{gem_dir}/* \
%{buildroot}%{gem_dir}

if [ -d .%{_bindir} ]; then
mkdir -p %{buildroot}%{_bindir}
cp -pa .%{_bindir}/* \
%{buildroot}%{_bindir}/
fi

%check
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost
pushd %{buildroot}%{gem_dir}/gems/bson-3.2.6
rspec -I.:lib spec/
popd


%files
%defattr(-,root,root,-)
/usr/lib64/ruby/gems/2.3.0/cache/bson-3.2.6.gem
/usr/lib64/ruby/gems/2.3.0/extensions/x86_64-linux/2.3.0/bson-3.2.6/gem.build_complete
/usr/lib64/ruby/gems/2.3.0/extensions/x86_64-linux/2.3.0/bson-3.2.6/gem_make.out
/usr/lib64/ruby/gems/2.3.0/gems/bson-3.2.6/CHANGELOG.md
/usr/lib64/ruby/gems/2.3.0/gems/bson-3.2.6/CONTRIBUTING.md
/usr/lib64/ruby/gems/2.3.0/gems/bson-3.2.6/LICENSE
/usr/lib64/ruby/gems/2.3.0/gems/bson-3.2.6/NOTICE
/usr/lib64/ruby/gems/2.3.0/gems/bson-3.2.6/README.md
/usr/lib64/ruby/gems/2.3.0/gems/bson-3.2.6/Rakefile
/usr/lib64/ruby/gems/2.3.0/gems/bson-3.2.6/ext/bson/.RUBYARCHDIR.time
/usr/lib64/ruby/gems/2.3.0/gems/bson-3.2.6/ext/bson/Makefile
/usr/lib64/ruby/gems/2.3.0/gems/bson-3.2.6/ext/bson/extconf.rb
/usr/lib64/ruby/gems/2.3.0/gems/bson-3.2.6/ext/bson/native.c
/usr/lib64/ruby/gems/2.3.0/gems/bson-3.2.6/ext/bson/native.o
/usr/lib64/ruby/gems/2.3.0/gems/bson-3.2.6/lib/bson.rb
/usr/lib64/ruby/gems/2.3.0/gems/bson-3.2.6/lib/bson/array.rb
/usr/lib64/ruby/gems/2.3.0/gems/bson-3.2.6/lib/bson/binary.rb
/usr/lib64/ruby/gems/2.3.0/gems/bson-3.2.6/lib/bson/boolean.rb
/usr/lib64/ruby/gems/2.3.0/gems/bson-3.2.6/lib/bson/code.rb
/usr/lib64/ruby/gems/2.3.0/gems/bson-3.2.6/lib/bson/code_with_scope.rb
/usr/lib64/ruby/gems/2.3.0/gems/bson-3.2.6/lib/bson/date.rb
/usr/lib64/ruby/gems/2.3.0/gems/bson-3.2.6/lib/bson/date_time.rb
/usr/lib64/ruby/gems/2.3.0/gems/bson-3.2.6/lib/bson/document.rb
/usr/lib64/ruby/gems/2.3.0/gems/bson-3.2.6/lib/bson/encodable.rb
/usr/lib64/ruby/gems/2.3.0/gems/bson-3.2.6/lib/bson/environment.rb
/usr/lib64/ruby/gems/2.3.0/gems/bson-3.2.6/lib/bson/false_class.rb
/usr/lib64/ruby/gems/2.3.0/gems/bson-3.2.6/lib/bson/float.rb
/usr/lib64/ruby/gems/2.3.0/gems/bson-3.2.6/lib/bson/hash.rb
/usr/lib64/ruby/gems/2.3.0/gems/bson-3.2.6/lib/bson/int32.rb
/usr/lib64/ruby/gems/2.3.0/gems/bson-3.2.6/lib/bson/int64.rb
/usr/lib64/ruby/gems/2.3.0/gems/bson-3.2.6/lib/bson/integer.rb
/usr/lib64/ruby/gems/2.3.0/gems/bson-3.2.6/lib/bson/json.rb
/usr/lib64/ruby/gems/2.3.0/gems/bson-3.2.6/lib/bson/max_key.rb
/usr/lib64/ruby/gems/2.3.0/gems/bson-3.2.6/lib/bson/min_key.rb
/usr/lib64/ruby/gems/2.3.0/gems/bson-3.2.6/lib/bson/nil_class.rb
/usr/lib64/ruby/gems/2.3.0/gems/bson-3.2.6/lib/bson/object.rb
/usr/lib64/ruby/gems/2.3.0/gems/bson-3.2.6/lib/bson/object_id.rb
/usr/lib64/ruby/gems/2.3.0/gems/bson-3.2.6/lib/bson/regexp.rb
/usr/lib64/ruby/gems/2.3.0/gems/bson-3.2.6/lib/bson/registry.rb
/usr/lib64/ruby/gems/2.3.0/gems/bson-3.2.6/lib/bson/specialized.rb
/usr/lib64/ruby/gems/2.3.0/gems/bson-3.2.6/lib/bson/string.rb
/usr/lib64/ruby/gems/2.3.0/gems/bson-3.2.6/lib/bson/symbol.rb
/usr/lib64/ruby/gems/2.3.0/gems/bson-3.2.6/lib/bson/time.rb
/usr/lib64/ruby/gems/2.3.0/gems/bson-3.2.6/lib/bson/timestamp.rb
/usr/lib64/ruby/gems/2.3.0/gems/bson-3.2.6/lib/bson/true_class.rb
/usr/lib64/ruby/gems/2.3.0/gems/bson-3.2.6/lib/bson/undefined.rb
/usr/lib64/ruby/gems/2.3.0/gems/bson-3.2.6/lib/bson/version.rb
/usr/lib64/ruby/gems/2.3.0/gems/bson-3.2.6/spec/bson/array_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/bson-3.2.6/spec/bson/binary_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/bson-3.2.6/spec/bson/boolean_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/bson-3.2.6/spec/bson/code_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/bson-3.2.6/spec/bson/code_with_scope_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/bson-3.2.6/spec/bson/date_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/bson-3.2.6/spec/bson/date_time_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/bson-3.2.6/spec/bson/document_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/bson-3.2.6/spec/bson/false_class_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/bson-3.2.6/spec/bson/float_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/bson-3.2.6/spec/bson/hash_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/bson-3.2.6/spec/bson/int32_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/bson-3.2.6/spec/bson/int64_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/bson-3.2.6/spec/bson/integer_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/bson-3.2.6/spec/bson/json_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/bson-3.2.6/spec/bson/max_key_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/bson-3.2.6/spec/bson/min_key_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/bson-3.2.6/spec/bson/nil_class_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/bson-3.2.6/spec/bson/object_id_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/bson-3.2.6/spec/bson/object_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/bson-3.2.6/spec/bson/regexp_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/bson-3.2.6/spec/bson/registry_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/bson-3.2.6/spec/bson/string_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/bson-3.2.6/spec/bson/symbol_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/bson-3.2.6/spec/bson/time_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/bson-3.2.6/spec/bson/timestamp_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/bson-3.2.6/spec/bson/true_class_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/bson-3.2.6/spec/bson/undefined_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/bson-3.2.6/spec/bson_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/bson-3.2.6/spec/spec_helper.rb
/usr/lib64/ruby/gems/2.3.0/gems/bson-3.2.6/spec/support/shared_examples.rb
/usr/lib64/ruby/gems/2.3.0/specifications/bson-3.2.6.gemspec

%files lib
%defattr(-,root,root,-)
/usr/lib64/ruby/gems/2.3.0/extensions/x86_64-linux/2.3.0/bson-3.2.6/native.so
/usr/lib64/ruby/gems/2.3.0/gems/bson-3.2.6/ext/bson/native.so
/usr/lib64/ruby/gems/2.3.0/gems/bson-3.2.6/lib/native.so
